"""Add reviewer_comment to QueryApproval

Revision ID: 3c040badd2cd
Revises: d8c81f55907b
Create Date: 2026-01-18 13:36:04.779625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3c040badd2cd'
down_revision: Union[str, Sequence[str], None] = 'd8c81f55907b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('query_approvals', sa.Column('reviewer_comment', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('query_approvals', 'reviewer_comment')
    # ### end Alembic commands ###
