"""create query_history table

Revision ID: 6f33e21a25cd
Revises: 3c040badd2cd
Create Date: 2026-01-18 14:28:51.721129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6f33e21a25cd'
down_revision: Union[str, Sequence[str], None] = '3c040badd2cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('queryhistory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('generated_sql', sa.Text(), nullable=True),
    sa.Column('intent', sa.String(length=50), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('is_ambiguous', sa.Boolean(), nullable=True),
    sa.Column('insights', sa.JSON(), nullable=True),
    sa.Column('execution_status', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['connection_id'], ['db_connection.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_queryhistory_id'), 'queryhistory', ['id'], unique=False)
    # op.drop_table('livonia_cdb')
    # op.drop_table('ai_extracted_livonia_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_extracted_livonia_data',
    sa.Column('Filename', mysql.TEXT(), nullable=True),
    sa.Column('Invoice_Number', mysql.TEXT(), nullable=True),
    sa.Column('Invoice_Date', sa.DATE(), nullable=True),
    sa.Column('Vendor', mysql.TEXT(), nullable=True),
    sa.Column('Item_Number', mysql.TEXT(), nullable=True),
    sa.Column('Unit_Prices', mysql.TEXT(), nullable=True),
    sa.Column('FilePath', mysql.TEXT(), nullable=True),
    sa.Column('Remark', mysql.TEXT(), nullable=True),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('livonia_cdb',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('Item_Number', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Unit_Prices', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('Source_File', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('Source_Company', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_index(op.f('ix_queryhistory_id'), table_name='queryhistory')
    op.drop_table('queryhistory')
    # ### end Alembic commands ###
