"""Initial_Schema_Complete

Revision ID: 7faf962c2022
Revises: 
Create Date: 2026-01-12 20:00:27.545002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7faf962c2022'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('db_connection', sa.Column('password_encrypted', sa.Text(), nullable=True))
    op.add_column('db_connection', sa.Column('connection_mode', sa.String(length=50), nullable=True))
    op.add_column('db_connection', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.drop_column('db_connection', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('db_connection', sa.Column('password', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('db_connection', 'is_active')
    op.drop_column('db_connection', 'connection_mode')
    op.drop_column('db_connection', 'password_encrypted')
    # ### end Alembic commands ###
