"""Add LLM config to User

Revision ID: d8c81f55907b
Revises: 7faf962c2022
Create Date: 2026-01-13 00:08:29.539372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd8c81f55907b'
down_revision: Union[str, Sequence[str], None] = '7faf962c2022'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Removing drop_table commands to preserve existing data
    op.add_column('user', sa.Column('llm_provider', sa.String(length=50), nullable=True))
    op.add_column('user', sa.Column('llm_model', sa.String(length=100), nullable=True))
    op.add_column('user', sa.Column('llm_api_key_encrypted', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'llm_api_key_encrypted')
    op.drop_column('user', 'llm_model')
    op.drop_column('user', 'llm_provider')
    # ### end Alembic commands ###
